dbt_project:
  outputs:
    dev:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      host: "{{ env_var('DBT_HOST') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      port: "{{ env_var('DBT_PORT') | as_number }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS') | as_number }}"
      type: "{{ env_var('DBT_TYPE') }}"
      user: "{{ env_var('DBT_USER') }}"
  target: dev