dbt_project:
  outputs:
    dev:
      type: duckdb
      path: /tmp/dbt.duckdb
      extensions:
        - httpfs
        - parquet
      secrets:
        - type: s3
          region: my-aws-region
          key_id: "{{ env_var('../../S3_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('../../S3_SECRET_ACCESS_KEY') }}"
  target: dev