dbt_project:
  outputs:
    dev:
      type: duckdb
      path: /tmp/dbt.duckdb
      filesystems:
        - fs: s3
          anon: false
          key: "minio-admin-user"
          secret: "minio-admin-pass"
          client_kwargs:
            endpoint_url: "http://localhost:9000"  # MinIO endpoint
  target: dev